name: stagexl_dragonbones
version: 0.2.2
author: Bernhard Pichler <support@stagexl.org>
description: The DragonBones runtime for the StageXL library.
homepage: http://www.stagexl.org

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  browser: any
  stagexl: '^1.0.0'

transformers:
- $dart2js:
    commandLineOptions: ["--trust-type-annotations", "--trust-primitives"]
    minify: true
