name: stagexl_dragonbones
version: 0.3.0
author: Bernhard Pichler <support@stagexl.org>
description: The DragonBones runtime for the StageXL library.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.0 <2.0.0'

dev_dependencies:
  build_test: ^0.10.3+1
  build_runner: ^0.10.1
  build_web_compilers: ^0.4.2+1
