name: stagexl_dragonbones
version: 0.3.2
author: Bernhard Pichler <support@stagexl.org>
description: The DragonBones runtime for the StageXL library.
homepage: http://www.stagexl.org

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  stagexl: '>=1.4.6 <2.0.0'

dev_dependencies:
  pedantic: any
  build_test: any
  build_runner: any
  build_web_compilers: any
